name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.2]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies 
      run: |
        pip install -r requirements.txt
    - name: Apply migration
      run: |
        python manage.py makemigrations 
        python manage.py migrate 
    #- name: drop database
      #run: |
       # DROP DATABASE IF EXISTS test_postgres;
    - name: Run Tests
      run: |
        python manage.py test userAccount
    


