name: Django CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:latest
                ports:
                    - 5432:5432
                env:
                    POSTGRES_DB: test_db
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r backend/requirements.txt

            - name: Set up PostgreSQL
              run: sudo apt-get install libpq-dev

            - name: Test for userAccount
              run: python backend/manage.py test userAccount --settings=covidVisionX.settings_test
              env:
                  DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db

            - name: Test for accessControl
              run: python backend/manage.py test accessControl --settings=covidVisionX.settings_test
              env:
                  DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
